### PR TITLE
fix: make inline styles work again

### PR DESCRIPTION
**Pull request by schelmo**

### CODE REVIEW

**Comment by schelmo** [comment]
of course not inline styles but sfc style tags :)

**Comment by adam-nygate** [comment]
Hey @schelmo, do you think this PR would resolve this bug? windicss/nuxt-windicss-module#17

**Comment by schelmo** [comment]
I dont know, but style tags will be parsed again. i tried some things with nuxt yesterday and found this bug. but the build progress didnt stall. 
maybe you can try to make a minimal reproduction repo for windicss/nuxt-windicss-module#17 ?
or maybe you can see something in the nuxt debug logs (https://nuxtjs.org/docs/2.x/internals-glossary/nuxt#debug-logs)
also you could try to add apply this fix to node_modules/windicss-webpack-plugin/dist/loaders/transform-template.js and see if it resolves the issue

**Comment by adam-nygate** [comment]
I manually applied the fix and it, unfortunately, does not resolve the issue.

I've enabled debug logging with no success. Unfortunately, there's no error and the @virtual/windi.css generates fine, but nuxt just stalls its build at compiling client

**Comment by loonpwn** [comment]
Oops, that was a dumb mistake. Thanks @schelmo.

Will be looking at setting up proper tests real soon to avoid this in the future

**Pull request merged**
